name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'hello'
        required: false
        default: 'development'
        type: string
  repository_dispatch:
    types: [build-and-test, deploy-trigger]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo 'Hello world'
