name: My deploy training
run-name: Deploy to ${{ github.actor }}
on:
  push:
    branches: [main, 'feature/**']
env:
  DAY_OF_WEEK: Monday
jobs:
  prod-check:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world $DAY_OF_WEEK"
