name: Test FastAPI API

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TESTING: "true"
      DATABASE_URL: sqlite+aiosqlite:///./test.db
    steps:
      - name: checkout
        uses: actions/checkout@v5
        
      - name: downloading python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          
      - name: downloading requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run tests
        env:
          PYTHONPATH: .
        run: pytest -v
